//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopPhone
{
    using System;
    using System.Collections.Generic;
    
    public partial class gallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gallery()
        {
            this.rela_phone_gallery = new HashSet<rela_phone_gallery>();
        }
    
        public int id_gallery { get; set; }
        public string gallery_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rela_phone_gallery> rela_phone_gallery { get; set; }
    }
}
