//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopPhone
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phone()
        {
            this.rela_phone_gallery = new HashSet<rela_phone_gallery>();
        }
    
        public int id_phone { get; set; }
        public string phone_name { get; set; }
        public string description { get; set; }
        public string image_feature { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> id_brand { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual rela_brand_phone rela_brand_phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rela_phone_gallery> rela_phone_gallery { get; set; }
    }
}
