//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopPhone
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShopDienThoaiEntities : DbContext
    {
        public ShopDienThoaiEntities()
            : base("name=ShopDienThoaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<gallery> galleries { get; set; }
        public virtual DbSet<phone> phones { get; set; }
        public virtual DbSet<rela_brand_phone> rela_brand_phone { get; set; }
        public virtual DbSet<rela_phone_gallery> rela_phone_gallery { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual ObjectResult<phone> SP_PageList(Nullable<int> page, Nullable<int> quantity_row, ObjectParameter total)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var quantity_rowParameter = quantity_row.HasValue ?
                new ObjectParameter("quantity_row", quantity_row) :
                new ObjectParameter("quantity_row", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phone>("SP_PageList", pageParameter, quantity_rowParameter, total);
        }
    
        public virtual ObjectResult<phone> SP_PageList(Nullable<int> page, Nullable<int> quantity_row, ObjectParameter total, MergeOption mergeOption)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var quantity_rowParameter = quantity_row.HasValue ?
                new ObjectParameter("quantity_row", quantity_row) :
                new ObjectParameter("quantity_row", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phone>("SP_PageList", mergeOption, pageParameter, quantity_rowParameter, total);
        }
    
        public virtual int SP_PageList_RETURN(Nullable<int> page, Nullable<int> quantity_row)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var quantity_rowParameter = quantity_row.HasValue ?
                new ObjectParameter("quantity_row", quantity_row) :
                new ObjectParameter("quantity_row", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PageList_RETURN", pageParameter, quantity_rowParameter);
        }
    }
}
